schema_version = 1
plugin_id = "org.jeschete.retroarch-overlay.dragonwarrior3"
slug = "dragonwarrior3"
name = "Dragon Warrior 3"
api_version = 1
entry = "plugin.py"
license = "MIT"
ra_game_id = 1667

[match]
cores = []
content_hints = ["dragonwarrior3"]
hashes = [
    "16a03048ce659d3d733026b6b72f2470",
    "53c1b36072390deb0c1f4d435cf2e41f",
    "57bc5e42907f566990514eb57dee296c",
    "5a0c984006b088c26db5a4f454b7a0ef",
    "615931aa63a3392891d4c8e768ee7ada",
    "b4b5416962ac800a77a0cf756bfd3fa0",
]

[[sources]]
id = "dragonwarrior3"
kind = "git-submodule"
path = "decomp_reference/DragonWarrior3"
required = false
url = "https://github.com/zeromus/DragonWarrior3.git"
required_files = []
